# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # client
  - package-ecosystem: "npm"
    directory: "/client"
    target-branch: "dev" # Теперь PR будут приходить в dev
    schedule:
      interval: "daily"

  # server
  - package-ecosystem: "npm"
    directory: "/server"
    target-branch: "dev" # И здесь тоже в dev
    schedule:
      interval: "daily"
