version: "3.8"

services:
  server:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/partner-server-prod:latest
    container_name: partner-server-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./uploads:/app/uploads

  client:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/partner-client-prod:latest
    container_name: partner-client-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
